#!/usr/bin/env python3
"""gen_camddriver.py — turn the linked CAMD MIDI driver (a HUNK exe) into CAMDDriver.c.

The camdusbmidi class embeds the driver as a `ULONG[]` and writes it to DEVS:Midi/<id>
at bind time (the `#if __mc68000__` path), patching the driver's name string per unit.
This replaces the frozen 2006 blob with the freshly built driver and co-emits the
name-string offset (which moves whenever the driver is recompiled), so the class never
hardcodes it.

Usage: gen_camddriver.py <driver-binary> <out-CAMDDriver.c>
"""
import sys, struct

HUNK_CODE = b'\x00\x00\x03\xe9'
STUB_MAGIC = b'\x70\xff\x4e\x75\x4d\x44\x45\x56'  # `moveq #-1,d0; rts` + 'MDEV'
NAME = b'poseidonusb'

def main():
    src, dst = sys.argv[1], sys.argv[2]
    data = open(src, 'rb').read()
    if len(data) % 4:
        data += b'\x00' * (4 - len(data) % 4)

    # Layout guarantee: the first code hunk's body must begin with the do-not-execute
    # stub immediately followed by MidiDeviceData's MDD_Magic ('MDEV') — i.e. camd.library
    # finds the table at offset 4 of the loaded image. (8 = HUNK_CODE marker + size long.)
    hc = data.find(HUNK_CODE)
    if hc < 0:
        sys.exit("gen_camddriver: no HUNK_CODE in %s" % src)
    body = data[hc + 8:hc + 16]
    if body != STUB_MAGIC:
        sys.exit("gen_camddriver: CAMD layout broken — first code hunk must start with "
                 "`moveq #-1,d0; rts` + 'MDEV', got %r" % body)

    # Name string offset (the class strcpy()s the per-unit id over it).
    off = data.find(NAME)
    if off < 0:
        sys.exit("gen_camddriver: name string %r not found" % NAME)
    if data[off + len(NAME)] != 0:
        sys.exit("gen_camddriver: name string not NUL-terminated at 0x%x" % off)

    words = struct.unpack('>%dL' % (len(data) // 4), data)
    with open(dst, 'w') as f:
        f.write("/* AUTO-GENERATED by camd/gen_camddriver.py from camd/poseidonusb — do not edit. */\n")
        f.write("/* The embedded CAMD MIDI driver (a HUNK exe); the class writes it to\n")
        f.write(" * DEVS:Midi/<id> at bind time and patches the name at CAMDDriver_NAMEOFFSET. */\n")
        f.write("static const ULONG CAMDDriver[] = {\n")
        for i in range(0, len(words), 8):
            f.write("    " + " ".join("0x%08X," % w for w in words[i:i + 8]) + "\n")
        f.write("};\n")
        f.write('#define CAMDDriver_NAMEOFFSET 0x%X  /* byte offset of name[]="poseidonusb" */\n' % off)

if __name__ == '__main__':
    main()
